In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("c:/users/sakshi yadav/Downloads/Grocery_dataset.csv")

In [3]:
df.head()

   Member_number        Date   itemDescription
0           1808  21-07-2015    tropical fruit
1           2552  05-01-2015        whole milk
2           2300  19-09-2015         pip fruit
3           1187  12-12-2015  other vegetables
4           3037  01-02-2015        whole milk

In [4]:
df.shape

(38765, 3)

In [5]:
df.itemDescription.unique()

array(['tropical fruit', 'whole milk', 'pip fruit', 'other vegetables',
       'rolls/buns', 'pot plants', 'citrus fruit', 'beef', 'frankfurter',
       'chicken', 'butter', 'fruit/vegetable juice',
       'packaged fruit/vegetables', 'chocolate', 'specialty bar',
       'butter milk', 'bottled water', 'yogurt', 'sausage', 'brown bread',
       'hamburger meat', 'root vegetables', 'pork', 'pastry',
       'canned beer', 'berries', 'coffee', 'misc. beverages', 'ham',
       'turkey', 'curd cheese', 'red/blush wine',
       'frozen potato products', 'flour', 'sugar', 'frozen meals',
       'herbs', 'soda', 'detergent', 'grapes', 'processed cheese', 'fish',
       'sparkling wine', 'newspapers', 'curd', 'pasta', 'popcorn',
       'finished products', 'beverages', 'bottled beer', 'dessert',
       'dog food', 'specialty chocolate', 'condensed milk', 'cleaner',
       'white wine', 'meat', 'ice cream', 'hard cheese', 'cream cheese ',
       'liquor', 'pickled vegetables', 'liquor (appetizer)', 'UHT-milk',
       'candy', 'onions', 'hair spray', 'photo/film', 'domestic eggs',
       'margarine', 'shopping bags', 'salt', 'oil', 'whipped/sour cream',
       'frozen vegetables', 'sliced cheese', 'dish cleaner',
       'baking powder', 'specialty cheese', 'salty snack',
       'Instant food products', 'pet care', 'white bread',
       'female sanitary products', 'cling film/bags', 'soap',
       'frozen chicken', 'house keeping products', 'spread cheese',
       'decalcifier', 'frozen dessert', 'vinegar', 'nuts/prunes',
       'potato products', 'frozen fish', 'hygiene articles',
       'artif. sweetener', 'light bulbs', 'canned vegetables',
       'chewing gum', 'canned fish', 'cookware', 'semi-finished bread',
       'cat food', 'bathroom cleaner', 'prosecco', 'liver loaf',
       'zwieback', 'canned fruit', 'frozen fruits', 'brandy',
       'baby cosmetics', 'spices', 'napkins', 'waffles', 'sauces', 'rum',
       'chocolate marshmallow', 'long life bakery product', 'bags',
       'sweet spreads', 'soups', 'mustard', 'specialty fat',
       'instant coffee', 'snack products', 'organic sausage',
       'soft cheese', 'mayonnaise', 'dental care', 'roll products ',
       'kitchen towels', 'flower soil/fertilizer', 'cereals',
       'meat spreads', 'dishes', 'male cosmetics', 'candles', 'whisky',
       'tidbits', 'cooking chocolate', 'seasonal products', 'liqueur',
       'abrasive cleaner', 'syrup', 'ketchup', 'cream', 'skin care',
       'rubbing alcohol', 'nut snack', 'cocoa drinks', 'softener',
       'organic products', 'cake bar', 'honey', 'jam', 'kitchen utensil',
       'flower (seeds)', 'rice', 'tea', 'salad dressing',
       'specialty vegetables', 'pudding powder', 'ready soups',
       'make up remover', 'toilet cleaner', 'preservation products'],
      dtype=object)

In [6]:
len(df.itemDescription.unique())

167

In [7]:
len(df.Member_number.unique())

3898

In [8]:
member_id = df.Member_number.unique()

In [9]:
member_id

array([1808, 2552, 2300, ..., 3607, 4587, 2417], shape=(3898,))

In [13]:
data = list()

In [14]:
for m_id in member_id:
    data.append(list(df[df['Member_number']==m_id].itemDescription))

In [17]:
data[:2]

[['tropical fruit',
  'long life bakery product',
  'meat',
  'sugar',
  'rolls/buns',
  'semi-finished bread',
  'whole milk',
  'citrus fruit',
  'candy',
  'napkins'],
 ['whole milk',
  'butter',
  'female sanitary products',
  'pot plants',
  'other vegetables',
  'tropical fruit',
  'root vegetables',
  'whole milk',
  'shopping bags',
  'chocolate',
  'chocolate',
  'coffee',
  'hygiene articles']]

In [18]:
from mlxtend.preprocessing import TransactionEncoder

In [19]:
te = TransactionEncoder()
tranc = te.fit(data).transform(data)

In [21]:
tranc[:1]

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False,  True, False, False, False, False, False, False, False,
        False, False, False,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False, False, False,
         True, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False,  True, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True, False, False,
        False, False, False,  True, False, False, False, False, False,
        False, False,  True, False, False]])

In [22]:
df = pd.DataFrame(tranc, columns=te.columns_)

In [23]:
df.head()

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,False,False

In [24]:
from mlxtend.frequent_patterns import apriori, association_rules

In [25]:
s_tra = apriori(df, min_support=0.1, use_colnames=True)

In [26]:
s_tra

     support                        itemsets
0   0.119548                          (beef)
1   0.158799                  (bottled beer)
2   0.213699                 (bottled water)
3   0.135967                   (brown bread)
4   0.126475                        (butter)
5   0.165213                   (canned beer)
6   0.100564                       (chicken)
7   0.185480                  (citrus fruit)
8   0.114931                        (coffee)
9   0.120831                          (curd)
10  0.133145                 (domestic eggs)
11  0.137506                   (frankfurter)
12  0.102617             (frozen vegetables)
13  0.124936         (fruit/vegetable juice)
14  0.116983                     (margarine)
15  0.139815                    (newspapers)
16  0.376603              (other vegetables)
17  0.177527                        (pastry)
18  0.170600                     (pip fruit)
19  0.132376                          (pork)
20  0.349666                    (rolls/buns)
21  0.230631               (root vegetables)
22  0.206003                       (sausage)
23  0.168291                 (shopping bags)
24  0.313494                          (soda)
25  0.233710                (tropical fruit)
26  0.154695            (whipped/sour cream)
27  0.458184                    (whole milk)
28  0.282966                        (yogurt)
29  0.112365     (bottled water, whole milk)
30  0.146742  (rolls/buns, other vegetables)
31  0.124166        (other vegetables, soda)
32  0.191380  (other vegetables, whole milk)
33  0.120318      (yogurt, other vegetables)
34  0.119805              (rolls/buns, soda)
35  0.178553        (rolls/buns, whole milk)
36  0.111339            (yogurt, rolls/buns)
37  0.113135   (root vegetables, whole milk)
38  0.106978           (sausage, whole milk)
39  0.151103              (soda, whole milk)
40  0.116470    (tropical fruit, whole milk)
41  0.150590            (yogurt, whole milk)

In [27]:
rules = association_rules(s_tra, metric='confidence', min_threshold=0.3)

In [28]:
rules[['antecedents','consequents','support','lift','confidence']]

           antecedents         consequents   support      lift  confidence
0      (bottled water)        (whole milk)  0.112365  1.147597    0.525810
1         (rolls/buns)  (other vegetables)  0.146742  1.114335    0.419663
2   (other vegetables)        (rolls/buns)  0.146742  1.114335    0.389646
3   (other vegetables)              (soda)  0.124166  1.051695    0.329700
4               (soda)  (other vegetables)  0.124166  1.051695    0.396072
5   (other vegetables)        (whole milk)  0.191380  1.109106    0.508174
6         (whole milk)  (other vegetables)  0.191380  1.109106    0.417693
7             (yogurt)  (other vegetables)  0.120318  1.129050    0.425204
8   (other vegetables)            (yogurt)  0.120318  1.129050    0.319482
9         (rolls/buns)              (soda)  0.119805  1.092928    0.342627
10              (soda)        (rolls/buns)  0.119805  1.092928    0.382160
11        (rolls/buns)        (whole milk)  0.178553  1.114484    0.510638
12        (whole milk)        (rolls/buns)  0.178553  1.114484    0.389698
13            (yogurt)        (rolls/buns)  0.111339  1.125279    0.393472
14        (rolls/buns)            (yogurt)  0.111339  1.125279    0.318415
15   (root vegetables)        (whole milk)  0.113135  1.070630    0.490545
16           (sausage)        (whole milk)  0.106978  1.133394    0.519303
17              (soda)        (whole milk)  0.151103  1.051973    0.481997
18        (whole milk)              (soda)  0.151103  1.051973    0.329787
19    (tropical fruit)        (whole milk)  0.116470  1.087672    0.498353
20            (yogurt)        (whole milk)  0.150590  1.161510    0.532185
21        (whole milk)            (yogurt)  0.150590  1.161510    0.328667